https://sturdy-fiesta-976vq4wwrx37pqx-8000.app.github.dev/api/ponentes
use App\Http\Controllers\PonenteVistaController;
Route::get('/ponentes-vista',[PonenteVistaController::class,'index'])->name('ponentes.vista');
